# Base-image
FROM eclipse-temurin:21.0.11_10-jdk-alpine@sha256:1ff763083f2993d57d0bf374ab10bb3e2cb873af6c13a04458ebbd3e0337dc76 AS base

ARG ALPINE_REPO
ARG NODEJS_DIST_URL
ARG NPM_REPO
ARG PIP_CONFIG

ENV PATH=${PATH}:/usr/local/bin:/root/.local/bin \
    PYTHONPATH=/opt/pypi

COPY ci/images/common/mirrors.sh /tmp/common/mirrors.sh

RUN set -e; \
    . /tmp/common/mirrors.sh; \
    mirrors_on; \
    apk update \
 && apk add --no-cache --upgrade \
      bash \
      curl \
      expat \
      gcc \
      git \
      gradle \
      g++ \
      make \
      maven \
      musl-dev \
      nodejs \
      npm \
      python3 \
      python3-dev \
      py3-pip \
      py3-virtualenv \
      tar \
 && npm install -g corepack \
 && python3 --version \
 && python3 -m pip install \
      --break-system-packages \
      --no-cache-dir \
      --target ${PYTHONPATH} \
      --upgrade \
        atom-tools \
        pipenv \
 && node -v \
 && npm -v \
 && mvn -v \
 && gradle -v \
 && python3 --version \
 && rm -rf /var/cache/apk/* /tmp/common \
    && mirrors_off


# cdxgen-builder-image
FROM base AS cdxgen-builder

ARG ALPINE_REPO
ARG NODEJS_DIST_URL
ARG NPM_REPO
ARG PIP_CONFIG

ENV NODE_COMPILE_CACHE="/opt/cdxgen-node-cache"

COPY . /opt/cdxgen
COPY ci/images/common/ /tmp/common/

RUN sh /tmp/common/cdxgen-build.sh

# cdxgen-image
FROM base AS cdxgen

ENV CDXGEN_IN_CONTAINER=true \
    NODE_COMPILE_CACHE="/opt/cdxgen-node-cache" \
    PATH=${PATH}:${PYTHONPATH}/bin:/opt/cdxgen/node_modules/.bin

COPY --from=cdxgen-builder /opt/cdxgen /opt/cdxgen
COPY --from=cdxgen-builder /opt/cdxgen-node-cache /opt/cdxgen-node-cache

RUN chmod a-w -R /opt

WORKDIR /app

ENTRYPOINT ["node", "/opt/cdxgen/bin/cdxgen.js"]
